openapi: 3.0.3
info:
  title: Swagger Forex Calendar - OpenAPI 3.0
  description: |-
    This is a API for forex Calendar APP
    Some useful links:
    - [The Editor](https://editor.swagger.io/)
    - [The viewer](https://petstore.swagger.io//)
  contact:
    email: tradingads.io@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
  /availablecurrencies:
    get:
      tags:
        - Currency
      summary: Get list of available Currencies
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currencies'
  /event/getEvents:
    get:
      tags:
        - Event
      summary: Get events from server
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: "offset-date-time"
        - in: query
          name: country
          schema:
            type: string
        - in: query
          name: currency
          schema:
            type: string
        - in: query
          name: impact
          schema:
            type: string
            enum:
              - High
              - Medium
              - Low
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Events'
  /event/searchEvents:
    get:
      tags:
        - Event
      summary: Search events from server applying user preferences
      parameters:
        - in: query
          name: searchValue
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Events'
  /event/{name}:
    get:
      tags:
        - Event
      summary: Get full info about the event
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventInfo'
  /event/subscribe:
    post:
      tags:
        - Event
      summary: Subscribe Event
      parameters:
        - in: query
          name: recurring
          required: true
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Events'
      responses:
        '200':
          description: Successful operation
  /user/{id}/selectedCountries:
    post:
      tags:
        - User
      summary: Get coutries user is following
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: userId
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Countries'
  /user/{id}/configuration:
    get:
      tags:
        - User
      summary: Get user configuration
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: userId
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
    post:
      tags:
        - User
      summary: Get coutries user is following
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: userId
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
  /user/{id}/quiz:
    post:
      tags:
        - User
      summary: Upload Quiz
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: userId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '200':
          description: Successful operation
  /default/configuration:
    post:
      tags:
        - default
      summary: Get default configuration
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
  /default/currencies:
    get:
      tags:
        - default
      summary: Get list of preselected currencies in filter
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currencies'
components:
  schemas:
    Broker:
      type: object
      properties:
        description:
          type: string
        name:
          type: string
        image:
          type: string
          description: url
    Configuration:
      type: object
      properties:
        onboarding:
          $ref: '#/components/schemas/Onboarding'
        emails:
          type: array
          items:
            type: string
        mainMail:
          type: string
        name:
          type: string
        broker:
          $ref: '#/components/schemas/Broker'
        preferences:
          $ref: '#/components/schemas/Preferences'
    Preferences:
      type: object
      properties:
        impact:
          type: string
          enum:
            - High
            - Medium
            - Low
        timezone:
          type: string
        currencies:
          type: array
          items:
            type: string
          example: ["USD", "GBP"]
        countries:
          type: array
          items:
            type: string
          example: ["US", "GB"]
    Quiz:
      type: array
      items:
        $ref: '#/components/schemas/Question'
    Question:
      type: object
      properties:
        value:
          type: string
        response:
          type: string
    Onboarding:
      type: array
      items:
        $ref: '#/components/schemas/Screen'
    Screen:
      type: object
      properties:
        name:
          type: string
        value:
          type: boolean
      example:
        starting: true
    Currencies:
      type: array
      items:
        type: string
      example: ["USD", "GBP"]
    Countries:
      type: array
      items:
        type: string
      example: ["US", "GB"]
    Events:
      type: object
      properties:
        date:
          type: string
          format: "offset-date-time"
        country:
          type: string
        event:
          type: string
          description: name
        currency:
          type: string
        previous:
          type: number
          format: float
        estimate:
          type: number
          format: float
        actual:
          type: number
          format: float
        change:
          type: number
          format: float
        impact:
          type: string
        changePercentage:
          type: number
          format: float
      example:
        date: "2023-07-10 19:00:00"
        country: "US"
        event: "Consumer Credit Change (May)"
        currency: "USD"
        previous: 20.32
        estimate: 20.25
        actual: 7.24
        change: -13.08
        impact: "Low"
        changePercentage: -64.37
    News:
      type: object
      properties:
        url:
          type: string
        img:
          type: string
        text:
          type: string
    EventInfo:
      type: object
      properties:
        description:
          type: string
        news:
          type: array
          items:
            $ref: '#/components/schemas/News'
        date:
          type: string
          format: "offset-date-time"
        country:
          type: string
        event:
          type: string
          description: name
        currency:
          type: string
        previous:
          type: number
          format: float
        estimate:
          type: number
          format: float
        actual:
          type: number
          format: float
        change:
          type: number
          format: float
        impact:
          type: string
        changePercentage:
          type: number
          format: float
        pastEvents:
          type: array
          items:
            $ref: '#/components/schemas/News'
      example:
        date: "2023-07-10 19:00:00"
        country: "US"
        event: "Consumer Credit Change (May)"
        currency: "USD"
        previous: 20.32
        estimate: 20.25
        actual: 7.24
        change: -13.08
        impact: "Low"
        changePercentage: -64.37